### ISSUE TITLE
Grading call crashes when there is no student commit

### ISSUE THREAD

**Issue by rod-lin** [illinois-cs241/broadway-on-demand#72]
```
Traceback (most recent call last):
  File "/home/zl38/broadway-on-demand/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zl38/broadway-on-demand/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zl38/broadway-on-demand/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zl38/broadway-on-demand/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/zl38/broadway-on-demand/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zl38/broadway-on-demand/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zl38/broadway-on-demand/src/util.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/home/zl38/broadway-on-demand/src/auth.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/zl38/broadway-on-demand/src/routes_student.py", line 46, in student_get_assignment
    commit = get_latest_commit(netid, user["access_token"], course["github_org"])
  File "/home/zl38/broadway-on-demand/src/ghe_api.py", line 101, in get_latest_commit
    "No commits found."
KeyError: 'commit'
```
btw is this a typo?
https://github.com/illinois-cs241/broadway-on-demand/blob/master/src/ghe_api.py#L100
i.e. `latest_commit["message"]` instead of `latest_commit["commit"]["message"]`

**Comment by rod-lin** [comment]
nit but this line should probably handle the case where student_jobs_state is an empty map
https://github.com/illinois-cs241/broadway-on-demand/blob/master/src/bw_api.py#L117
if the preprocessing job crashes the student jobs would never be reached and the status would be "unknown"(since handler crashes here)

**Comment by rod-lin** [comment]
@shreyas208 how did you keep the list of `student_ids` in db sync'ed with the current roster?

**Comment by shreyas208** [comment]
@rod-lin there's no syncing right now 😶it's a manual change to the database
#20 , #67

**Comment by shreyas208** [comment]
@rod-lin yeah, the that `latest_commit` looks incorrect, we want `latest_commit["message"]`.
